### ISSUE TITLE
Can you please lock your dependencies

### ISSUE THREAD

**Issue by robertkraig** [dfcreative/define-state#1]
Consider updating your st8 dependency library to use a specific version instead of `latest` so that other libraries don't break. It caught me off guard using an old library called draggy which used define-state, and st8 library upgraded it's source to use the most modern / recent private class members.

It's not your library's fault, st8 refactored their stuff to be most recent iteration of node/es6 standards using `#privateMember` syntax.

**Comment by dy** [comment]
Sure. Please update define-state to v1.1.1.
Should work. Please close if it does.

**Comment by robertkraig** [comment]
Thank you, I appreciate that.
